export type ChangelogEntry = {
  version: string;
  date: string;
  title: string;
  highlights: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
  { version: "1.8.8", date: "2026-07-28", title: "Security Boundaries & Abuse Protection", highlights: ["Rate limit e limites de resposta nas Functions públicas", "Consultas e coordenadas protegidas contra cache compartilhado", "Validação central de URLs, imports JSON, temas, dashboards e ICS", "Service worker com caches limitados e mensagens validadas", "CSP de produção reforçada, dependências fixadas e varredura de release"] },
  { version: "1.8.7", date: "2026-07-28", title: "Security Hardening", highlights: ["Next.js atualizado para corrigir advisories de App Router, Server Actions, SSRF e cache", "Vitest, Vite e transitivas vulneráveis atualizadas ou fixadas por overrides", "Headers de segurança adicionados no Next.js e Netlify com CSP, COOP, Permissions-Policy e nosniff", "Service worker bloqueia navegação externa em cliques de notificação malformados", "Validação aprovada com lint, testes, build e audit de produção sem vulnerabilidades"] },
  { version: "1.8.6", date: "2026-07-28", title: "Documentation, Privacy & Storage Maintenance", highlights: ["Storage version 7 sincronizado na documentação", "Chaves de notícias removidas da lista duplicada sem trocar nomes canônicos", "Conteúdo externo bloqueado antes de chamadas opcionais quando desativado", "Textos legais alinhados a localStorage, Cache Storage, PWA e ausência de nuvem", "Script de pacote limpo com validação de artefatos e SHA-256"] },
  { version: "1.8.5", date: "2026-07-28", title: "Deep Modularization & Summary Domains", highlights: ["OverviewModule extraído do app principal", "Hooks dedicados para aba ativa, avatar, sync de dashboard e alertas de automação", "Rota /api/public/summary dividida por domínios de dados públicos", "Helpers compartilhados para fetch, tipos e normalização de payloads", "Checagem completa de lint, testes e build aprovada"] },
  { version: "1.8.4", date: "2026-07-28", title: "Shell Modularization & Release Prepare", highlights: ["Sidebar, topbar e notificações rápidas extraídos do shell principal", "Testes de UI por renderização para componentes do app shell", "Teste de renderização do painel de dados públicos com arte pública", "Script release:prepare para atualizar versões de forma consistente", "Cache PWA renovado para distribuir a modularização"] },
  { version: "1.8.3", date: "2026-07-27", title: "Structural Refactor & SW Hardening", highlights: ["Painel de dados públicos e busca global extraídos do shell principal", "Fontes públicas de conteúdo separadas da rota summary", "Service worker sem parsing de HTML gerado pelo Next.js", "Testes comportamentais para Art Institute e cache PWA", "Cache PWA renovado para distribuir a refatoração"] },
  { version: "1.8.2", date: "2026-07-27", title: "Public Art & Local Profile", highlights: ["Avatar do cabeçalho configurável com iniciais salvas no navegador", "Obra pública do dia via Art Institute of Chicago, sem chave de API", "Versão centralizada para PWA, Functions e User-Agent", "Mais preferências gravadas pelo gerenciador de armazenamento local", "Cache PWA renovado e validação completa com lint, testes e build"] },
  { version: "1.8.1", date: "2026-07-27", title: "Privacy & Legal Notice", highlights: ["Termos de Uso, Aviso de Privacidade e Política de Cookies e Armazenamento Local", "Banner de escolhas locais sem bloquear o uso essencial", "Publicidade e estatísticas desativadas até nova escolha", "Botão permanente para revisar preferências", "Consentimento versionado e incluído no backup local"] },
  { version: "1.8.0", date: "2026-07-27", title: "Themes & Template Gallery", highlights: ["Oito temas oficiais com densidade, arredondamento e sombras configuráveis", "Coleções de temas importáveis e exportáveis sem conta", "Tema global ou identidade visual diferente para cada layout", "Galeria com 16 modelos locais, busca, filtros, favoritos e pré-visualização", "Novos modelos para manhã, executivo, minimalista, turno noturno, fim de semana e agenda familiar", "Migração automática do sistema de temas para a versão 3"] },
  { version: "1.7.1", date: "2026-07-24", title: "Adaptive Desktop Hotfix", highlights: ["Conteúdo desktop passa a descontar corretamente a largura da sidebar fixa", "Sidebar compacta entra mais cedo em notebooks e janelas com zoom", "Pré-visualização e cartões laterais reorganizam sem sair da viewport", "Cabeçalhos e ações quebram linha sem cortar botões", "Mobile preservado sem alterações na navbar validada", "Cache PWA renovado para distribuir o CSS corrigido"] },
  { version: "1.7.0", date: "2026-07-24", title: "Calendar & Notifications", highlights: ["Calendário com visualizações de mês, semana, dia e lista", "Edição de uma ocorrência, desta e das próximas ou de toda a série", "Duração, local, múltiplos alertas e arquivos .ics enriquecidos", "Caixa de entrada local com lidos, histórico, adiamento e dispensa", "Horário silencioso e teste de notificações do navegador", "Resumo de produtividade, filtros e reagendamento otimizado para mobile"] },
  { version: "1.6.4", date: "2026-07-24", title: "Quality Gate & Build Validation", highlights: ["Lint compatível com React 19 e Next.js 16", "Estados derivados refatorados sem efeitos redundantes", "Navegação interna do display corrigida com next/link", "Validadores locais e avisos de código limpos", "Script PowerShell agora falha corretamente e detecta arquivos bloqueados", "Build corrigido para usar ícones compatíveis do lucide-react", "Configurações PostCSS antigas são removidas pelo verificador"] },
  { version: "1.6.3", date: "2026-07-24", title: "Deployment & Mobile Hotfix", highlights: ["Build local e Netlify estabilizado sem dependência do Tailwind", "Raiz do Turbopack fixada no diretório real do projeto", "Sino abre um painel de notificações funcional", "Navbar móvel isolada da página e protegida contra zoom", "Cache PWA renovado para distribuir os estilos corrigidos"] },
  { version: "1.6.2", date: "2026-07-24", title: "Mobile Navigation & Performance", highlights: ["Navegação móvel fixa em cinco posições com menu completo", "Cabeçalho e containers protegidos contra zoom, overflow e cortes", "Versão e resumo da release visíveis no painel", "CSS responsivo consolidado e carregamento visual mais estável", "Testes de viewport, navegação e cache PWA ampliados"] },
  { version: "1.6.1", date: "2026-07-23", title: "Responsive Experience", highlights: ["Cabeçalho compacto e sem cortes em celulares estreitos", "Navegação móvel completa e rolável para todos os módulos", "Grades, formulários, carrosséis, agenda, música e modais adaptados por breakpoint", "Áreas de toque, safe areas e rolagem interna aprimoradas", "Compatibilidade revisada para Android, iPhone, tablets e desktops ultrawide"] },
  { version: "1.6.0", date: "2026-07-23", title: "PWA & Offline Experience", highlights: ["Service worker, telas principais e dados recentes disponíveis offline", "Atualização controlada com backup e recuperação de segurança", "Central de notificações local", "Agenda mensal/semanal, subtarefas, recorrência avançada e .ics", "Editor de temas e dez modelos prontos", "Validação de backups, recuperação de dados e monitor de desempenho"] },
  { version: "1.5.0", date: "2026-07-23", title: "Visual Dashboard Studio", highlights: ["Editor visual e layouts múltiplos", "Playlists por horário e modo display", "Compartilhamento por link, QR e JSON", "Descoberta musical e rádios sem autenticação"] },
  { version: "1.4.0", date: "2026-07-23", title: "Agenda recorrente e anime", highlights: ["Recorrência diária, semanal, mensal e anual", "Carrosséis de tecnologia e anime", "Pesquisa de animes pelo Jikan"] },
  { version: "1.3.0", date: "2026-07-23", title: "Mais dados públicos", highlights: ["Economia, IBGE, terremotos e ambiente", "Livros, Wikipédia, TV e alimentos", "Consultas sob demanda sem chave"] },
  { version: "1.2.0", date: "2026-07-23", title: "Local-first funcional", highlights: ["Agenda e Pomodoro no localStorage", "Dados públicos sem chave", "Netlify Functions sem estado"] },
];
